import loginPage from "../../pageObject/loginPage"
import cartPage from "../../pageObject/cartPage"
const inputan = require('../../fixtures/demoblaze/data.json')

describe('Add to Cart - Cart Page Scenario', () => {
  const Login_Page = new loginPage()
  const Cart_Page = new cartPage()
  beforeEach(() => {
    cy.wait(700)
    cy.clearCookies()
    cy.visit('https://demoblaze.com')
  })

  it('Cart Page - Success Purchase With Login', () => {
    Login_Page.clickLogin1()
    Login_Page.inputUsername(inputan.valid_user)
    Login_Page.inputPassword(inputan.valid_pass)
    Login_Page.clickLogin2()
    Cart_Page.additem1()
    Cart_Page.addtocartBtn()
    Cart_Page.cart_Menu()

    Cart_Page.clickPOButton()
    Cart_Page.InputNameField(inputan.name_field)
    Cart_Page.InputCountryField(inputan.country_field)
    Cart_Page.InputCityField(inputan.city_field)
    Cart_Page.InputCardField(inputan.card_field)
    Cart_Page.InputMonthField(inputan.month_field)
    Cart_Page.InputYearField(inputan.year_field)
    Cart_Page.ClickPurchaseButton()
    Cart_Page.validate_success()
  })

  it('Cart Page - Purchase Without Login', () => {
    Cart_Page.additem1()
    Cart_Page.addtocartBtn()
    Cart_Page.cart_Menu()

    Cart_Page.clickPOButton()
    Cart_Page.InputNameField(inputan.name_field)
    Cart_Page.InputCountryField(inputan.country_field)
    Cart_Page.InputCityField(inputan.city_field)
    Cart_Page.InputCardField(inputan.card_field)
    Cart_Page.InputMonthField(inputan.month_field)
    Cart_Page.InputYearField(inputan.year_field)
    Cart_Page.ClickPurchaseButton()
    Cart_Page.validate_success()
  })

  it('Cart Page - Purchase Empty Name Order', () => {
    Login_Page.clickLogin1()
    Login_Page.inputUsername(inputan.valid_user)
    Login_Page.inputPassword(inputan.valid_pass)
    Login_Page.clickLogin2()
    Cart_Page.additem1()
    Cart_Page.addtocartBtn()
    Cart_Page.cart_Menu()

    Cart_Page.clickPOButton()
    Cart_Page.InputCountryField(inputan.country_field)
    Cart_Page.InputCityField(inputan.city_field)
    Cart_Page.InputCardField(inputan.card_field)
    Cart_Page.InputMonthField(inputan.month_field)
    Cart_Page.InputYearField(inputan.year_field)
    Cart_Page.ClickPurchaseButton()
    Cart_Page.validate_empty_name()
  })

  it('Cart Page - Purchase Empty Country', () => {
    Login_Page.clickLogin1()
    Login_Page.inputUsername(inputan.valid_user)
    Login_Page.inputPassword(inputan.valid_pass)
    Login_Page.clickLogin2()
    Cart_Page.additem1()
    Cart_Page.addtocartBtn()
    Cart_Page.cart_Menu()

    Cart_Page.clickPOButton()
    Cart_Page.InputNameField(inputan.name_field)
    Cart_Page.InputCityField(inputan.city_field)
    Cart_Page.InputCardField(inputan.card_field)
    Cart_Page.InputMonthField(inputan.month_field)
    Cart_Page.InputYearField(inputan.year_field)
    Cart_Page.ClickPurchaseButton()
    Cart_Page.validate_empty_country()
  })

  it('Cart Page - Purchase Empty City', () => {
    Login_Page.clickLogin1()
    Login_Page.inputUsername(inputan.valid_user)
    Login_Page.inputPassword(inputan.valid_pass)
    Login_Page.clickLogin2()
    Cart_Page.additem1()
    Cart_Page.addtocartBtn()
    Cart_Page.cart_Menu()

    Cart_Page.clickPOButton()
    Cart_Page.InputNameField(inputan.name_field)
    Cart_Page.InputCountryField(inputan.country_field)
    Cart_Page.InputCardField(inputan.card_field)
    Cart_Page.InputMonthField(inputan.month_field)
    Cart_Page.InputYearField(inputan.year_field)
    Cart_Page.ClickPurchaseButton()
    Cart_Page.validate_empty_city()
  })

  it('Cart Page - Purchase Empty Card', () => {
    Login_Page.clickLogin1()
    Login_Page.inputUsername(inputan.valid_user)
    Login_Page.inputPassword(inputan.valid_pass)
    Login_Page.clickLogin2()
    Cart_Page.additem1()
    Cart_Page.addtocartBtn()
    Cart_Page.cart_Menu()

    Cart_Page.clickPOButton()
    Cart_Page.InputNameField(inputan.name_field)
    Cart_Page.InputCountryField(inputan.country_field)
    Cart_Page.InputCityField(inputan.city_field)
    Cart_Page.InputMonthField(inputan.month_field)
    Cart_Page.InputYearField(inputan.year_field)
    Cart_Page.ClickPurchaseButton()
    Cart_Page.validate_empty_card()
  })

  it('Cart Page - Purchase Empty Month', () => {
    Login_Page.clickLogin1()
    Login_Page.inputUsername(inputan.valid_user)
    Login_Page.inputPassword(inputan.valid_pass)
    Login_Page.clickLogin2()
    Cart_Page.additem1()
    Cart_Page.addtocartBtn()
    Cart_Page.cart_Menu()

    Cart_Page.clickPOButton()
    Cart_Page.InputNameField(inputan.name_field)
    Cart_Page.InputCountryField(inputan.country_field)
    Cart_Page.InputCityField(inputan.city_field)
    Cart_Page.InputYearField(inputan.year_field)
    Cart_Page.ClickPurchaseButton()
    Cart_Page.validate_empty_month()
  })

  it('Cart Page - Purchase Empty Year', () => {
    Login_Page.clickLogin1()
    Login_Page.inputUsername(inputan.valid_user)
    Login_Page.inputPassword(inputan.valid_pass)
    Login_Page.clickLogin2()
    Cart_Page.additem1()
    Cart_Page.addtocartBtn()  
    Cart_Page.cart_Menu()

    Cart_Page.clickPOButton()
    Cart_Page.InputNameField(inputan.name_field)
    Cart_Page.InputCountryField(inputan.country_field)
    Cart_Page.InputCityField(inputan.city_field)
    Cart_Page.InputCardField(inputan.card_field)
    Cart_Page.InputMonthField(inputan.month_field)
    Cart_Page.ClickPurchaseButton()
    Cart_Page.validate_empty_year()
  })

  it('Cart Page - Delete Item', () => {
    Login_Page.clickLogin1()
    Login_Page.inputUsername(inputan.valid_user)
    Login_Page.inputPassword(inputan.valid_pass)
    Login_Page.clickLogin2()
    Cart_Page.additem1()
    Cart_Page.addtocartBtn()
    Cart_Page.cart_Menu()
    Cart_Page.clickDelete()
  })

})